### ISSUE TITLE
Features failing to start up

### ISSUE THREAD

**Issue by huntc** [typesafehub/sbt-conductr-sandbox#18] opened 2015-08-31 01:32 UTC
I tried out the `--with-features visualizer` for the first time and it failed. It seems that the curl is expected to work immediately, however it takes some time for the cluster to form. It perhaps takes longer on my machine than others. Here's the log:

```
 * Starting haproxy haproxy
   ...done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 2b145c9159a7 port 9005: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 2b145c9159a7 port 9005: Connection refused
        ????   Typesafe ConductR
    ????
????    ????   Version 0.1.0
    ????
????           Copyright ? 2014-2015 Typesafe, Inc. All rights reserved.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 2b145c9159a7 port 9005: Connection refused
01:20:16 ERROR BundlesConnector [akka://conductr/user/reaper/bundles-connector] - Bundles events connection closed
akka.stream.StreamTcpException: Connection failed.

Starting up with the following network settings:
  ip     : 172.17.0.82
  b-ip   : 172.17.0.82
  b-port : 9006
  cp-ip  : 172.17.0.82
  cp-port: 9005
  sl-ip  : 172.17.0.82
  sl-port: 9008
  ss-ip  : 172.17.0.82
  ss-port: 9007


01:20:17 ERROR BundlesConnector [akka://conductr/user/reaper/bundles-connector] - Bundles events connection closed
akka.stream.StreamTcpException: Connection failed.
01:20:19 ERROR BundlesConnector [akka://conductr/user/reaper/bundles-connector] - Bundles events connection closed
akka.stream.StreamTcpException: Connection failed.
01:20:20 ERROR BundlesConnector [akka://conductr/user/reaper/bundles-connector] - Bundles events connection closed
akka.stream.StreamTcpException: Connection failed.
01:20:21 ERROR BundlesConnector [akka://conductr/user/reaper/bundles-connector] - Bundles events connection closed
akka.stream.StreamTcpException: Connection failed.
01:20:21 ERROR BundlesConnector [akka://conductr/user/reaper/bundles-connector] - Bundles events connection closed
akka.stream.StreamTcpException: Connection failed.
01:20:22 ERROR BundlesConnector [akka://conductr/user/reaper/bundles-connector] - Bundles events connection closed
akka.stream.StreamTcpException: Connection failed.
```

**Comment by markusjura** [comment] 2015-08-31 07:06
I could reproduce that for the `visualization` feature for multiple apps. This problem only occurs for the visualization feature, not the logging feature.

It seems that in the current conductr version the visualizer bundle can't be found:

```
[ALERT] 242/070309 (293) : sendto logger #1 failed: No such file or directory (errno=2)
```

And therefor the visualizer is not loaded. Investigating further..

**Comment by markusjura** [comment] 2015-08-31 07:09
The following error messages are not the problem:

```
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 2b145c9159a7 port 9005: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
```

The conductr start script will try to connect to ConductR 30 times, every 2 seconds. Therefor in the beginning we'll see this error messages.

I'll make the curl command silent so that these error messages doesn't flood our log.

**Comment by markusjura** [comment] 2015-08-31 07:31
Turns out that it is not only related to the visualizer bundle. Before we are retrieving the `no such file or directory` error we are getting this:

```
No bundle found by the specified Bundle ID/name: 'conductr-elasticsearch'
```

Started the sandbox multiple times with both features `visualization` and `logging`. Always the first bundle of the first specified feature is started. Probably some raise condition. Investigating further..

**Comment by markusjura** [comment] 2015-08-31 10:59
**Final conclusion**
The `docker-entrypoint.py` script waits until conductr has been started before it loads the bundles of the features. This waiting logic was not correct. It only checked the curl exit code but not the curl response. If conductr is not running and empty string in the curl response was returned instead of a error ext code.

The waiting logic has been corrected with the PR https://github.com/typesafehub/conductr/pull/799.

**Comment by huntc** [comment] 2015-08-31 21:58
@markusjura Much better, but not totally reliable. I failed to see the Visualizer startup, again probably because the state hadn't replicated in time. Here's what I got from the logs:

```
08:33:17.240289 INFO ConductrStart: Bundle visualizer has been loaded..
08:33:17.240514 INFO ConductrStart: Scale bundle visualizer to 1 instance(s)..
No bundle found by the specified Bundle ID/name: 'visualizer'08:33:17.390318 INFO ConductrStart: Bundle visualizer is running..
```

**Comment by markusjura** [comment] 2015-09-01 06:36
We need to add a retry logic for loading a bundle. Only if the bundle has been loaded successfully we should continue with running / scaling the bundle. So far I've expected that loading always succeeds after ConductR has been started.

Only the seed node is triggering the loading and scaling, always on port 9005. So if ConductR is up and running as a seed node instance we should not have any problems with replication, right?

**Comment by markusjura** [comment] 2015-09-01 06:39
What happened in your case was that the loading of a bundle was not successful. Therefor you retrieved this error message:

```
No bundle found by the specified Bundle ID/name: 'visualizer'08:33:17.390318
```

**Comment by markusjura** [comment] 2015-09-01 11:10
Fixed with PR https://github.com/typesafehub/conductr/pull/809.

**Closed as completed** 2015-09-01 12:08 UTC
